export const items =[
    {
        id:"a",
        category:"aa",
        title:"aaa",
        innnerText:"aaaa"
    },
    {
        id:"b",
        category:"bb",
        title:"bbb",
        innnerText:"bbbb"
    },
    {
        id:"c",
        category:"cc",
        title:"ccc",
        innnerText:"cccc"
    },
    {
        id:"d",
        category:"dd",
        title:"ddd",
        innnerText:"dddd"
    },
]